# Generated by Django 6.1.1 on 2026-10-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'en attente'), ('confirmed', 'confirmé'), ('cancelled', 'annulé')], default='pending', max_length=20),
        ),
    ]
